import { type NextPage } from "next";
import Head from "next/head";
import DarkMode from "./DarkMode";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Plan - Prep - EAT!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center
      // for DARK MODE
      dark:bg-gradient-to-b from-[#342944] to-[#0d0e12] dark:text-white  text-black">
        <DarkMode />
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight dark:text-white sm:text-[5rem]">
            Plan <span className="text-[hsl(280,100%,70%)]">PREP</span> Eat
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <div
              className="flex max-w-xs flex-col gap-4 rounded-xl  bg-black/20 dark:bg-white/10 p-4 dark:text-white hover:bg-white/20"
            >
              <h3 className="text-2xl font-bold">Plan →</h3>
              <div className="text-lg">
                Let the head chef know what your preferences are:
              </div>
            </div>
            <div
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-black/20 dark:bg-white/10  p-4 dark:text-white hover:bg-white/20"
            >
              <h3 className="text-2xl font-bold">PREP →</h3>
              <div className="text-lg">
                Steps to prep:
                <div id="prep">

                </div>
              </div>
            </div>
          </div>
          <p className="text-2xl dark:text-white">
            Over to you... Eat Up!!
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
