import { type NextPage } from "next";
import Head from "next/head";
import DarkMode from "./DarkMode";
import { useState } from 'react';

import { api } from "~/utils/api";
import Switches from "./Switches";
import PantryStaples from "./PantryStaples";
import { defaultPantry } from "../store/defaultPantryStore";

import { Button, buttonVariants } from "../UI/button";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const [pantry, setPantry, selectedProtein] = defaultPantry((state) => [
    state.pantry,
    state.setPantry,
    state.selectedProtein,
  ]);

  const [result, setResult] = useState();

  async function onSubmit(event) {
    event.preventDefault();
    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        // second selectedProtein is from store line 16.
        body: JSON.stringify({ selectedProtein: selectedProtein }),
      });

      const data = await response.json();
      if (response.status !== 200) {
        throw data.error || new Error(`Request failed with status ${response.status}`);
      }

      setResult(data.result);
      // setAnimalInput("");
    } catch(error) {
      // Consider implementing your own error handling logic here
      console.error(error);
      alert(error.message);
    }
  }

  return (
    <>
      <Head>
        <title>Plan - Prep - EAT!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="// for DARK MODE flex
      min-h-screen flex-col items-center justify-center
      from-[#342944] to-[#0d0e12] text-black dark:bg-gradient-to-b  dark:text-white"
      >
        <DarkMode />
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-6 ">
          <h1 className="text-5xl font-extrabold tracking-tight dark:text-white sm:text-[5rem]">
            Plan <span className="text-[hsl(280,100%,70%)]">PREP</span> Eat
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <div className="flex max-w-xs flex-col gap-4 rounded-xl  bg-black/20 p-4 dark:bg-white/10 dark:text-white">
              <h3 className="text-2xl font-bold">Plan →</h3>
              <div className="text-lg">
                Let the head chef know what your preferences are:
              </div>
              {/* Switches used for the input data for search */}
              <Switches />
            </div>
            <div className="flex max-w-xs flex-col gap-4 rounded-xl bg-black/20 p-4  dark:bg-white/10 dark:text-white">
              <h3 className="text-2xl font-bold">PREP →</h3>
              <div className="text-lg">
                <div className="pb-4">
                  Remove any of the pantry staples that you DON'T have:
                </div>
                <PantryStaples />
                <div id="prep">
                  <div>Do you want to know the nutrients per serve?</div>
                  <div>Search the internet for a recipe</div>
                  <div className="mt-4 flex justify-center">
                    <Button
                      className={buttonVariants({
                        variant: "purple",
                        size: "",
                      })}
                      children={"SEARCH"}
                      onClick={onSubmit}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* delete prompt once working - will be used to enter into Chat GPT */}
          <div>Seach Prompt</div>
          <div className="flex">
            Provide a meal suggestion based around {selectedProtein} as the main ingredient.
            Assume the person has the following ingredients:
            {pantry.map((item, index) =>
              item.checked ? (
                <div className="pl-2" key={index}>
                  {item.item}
                </div>
              ) : null
            )}
          </div>
          <div className="flex">
            Assume the person does not have the following ingredients:
            {pantry.map((item, index) =>
              item.checked === false ? (
                <div className="pl-2" key={index}>
                  {item.item}
                </div>
              ) : null
            )}
          </div>
        </div>
        <div className="responseBox mb-5 flex h-[30vh] w-9/12 flex-col gap-4 rounded-xl  bg-black/20 p-4 dark:bg-white/10 dark:text-white">
          <div className="text-center text-2xl dark:text-white">
            Over to you... Eat Up!!!!

            {result}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
