# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build --if-present

    - name: Deploy to server
      env:
        PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        HOSTNAME: ${{ secrets.DEPLOY_HOST }}
        USER_NAME: ${{ secrets.USER_NAME }}

      run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
      
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 
 # 'deploy-command'
  
