# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
# CI is a series of Jobs
# Each Job, has a series of steps.

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    environment: "dev"

    runs-on: ubuntu-latest
    # Under the hood, Github is using Docker and the line above references to this. 

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.16
      uses: actions/setup-node@v3
      with:
        node-version: 18.16
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: ssh deploy on aws ec2
      uses: appleboy/ssh-action@v1.0.0
      with:
        DATABASE_URL: ${{ vars.DATABASE_URL }}
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: "build/"
        TARGET: ${{ secrets.DEPLOY_TARGET }}
         
   # test removed until TypeScript fixed
   # - run: npm test
