# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs


  
name: Node.js CI for next js app.

on:
  push:
    branches: [ "main" ]
 
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build --if-present


    - name: Create SSH Connection and SSH into Instance and Set Up
      env:
        PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        HOSTNAME: ${{ secrets.DEPLOY_HOST }}
        USER_NAME: ${{ secrets.DEPLOY_USER }}

      run: |
        echo "SSH connection successful"
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key

        # Start the SSH agent and add the private key
        eval $(ssh-agent -s)
        ssh-add private_key
            
        # SSH into the EC2 instance and set up the app directory

        ssh -v -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} "
        bash -c \'
        # Create a directory for your app
        mkdir -p /planApp
        # Move the built files to the app directory
        mv /app /planApp
        # Navigate to the app directory
        cd /planApp
        # Install dependencies and start the app (assuming Node.js)
        npm install
        pm2 start planApp
        \'"
